name: mla-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - librosa
  - pysoundfile
  - resampy
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - notebook
  - scikit-learn
  - keras
  - tensorflow

  